name: mediaforge

services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped

    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
      RUSTFS_CONSOLE_ENABLE: "true"

    ports:
      - "9010:9000"
      - "9011:9001"

    volumes:
      - rustfs_data:/data
    
volumes:
  postgres_data:
  rustfs_data: